pipeline:
  identifier: Build_kunalnano_juice_shop_1725034562262
  name: Build juice-shop
  orgIdentifier: TPMLabs
  projectIdentifier: testal
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1720712151481
        repoName: kunalnano/juice-shop
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    shell: Sh
                    command: |-
                      # Install n package to manage Node.js versions
                      npm install -g n
                      # Install Node.js version 18.19.0 or higher
                      n 18.19.0
                      # Verify Node.js version
                      node -v
                      npm -v
                      npm install eslint-plugin-n
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    shell: Sh
                    command: |-
                      cd frontend
                      npm install --legacy-peer-deps
                      npm install -g @angular/cli
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    shell: Sh
                    command: |-
                      # Change directory to the Angular workspace
                      cd frontend
                      # Run tests with the necessary Chrome flags
                      ng test --watch=false --source-map=true
              - step:
                  identifier: lint
                  name: lint
                  spec:
                    shell: Sh
                    command: |-
                      cd frontend
                      npm run lint
                  timeout: ""
                  type: Run
              - parallel:
                  - step:
                      identifier: dockerbuild
                      name: docker_build
                      spec:
                        connectorRef: <+input>
                        repo: alsharma9/juice-shop
                        tags:
                          - latest
                        caching: true
                      timeout: ""
                      type: BuildAndPushDockerRegistry
                  - step:
                      type: AquaTrivy
                      name: AquaTrivy_1
                      identifier: AquaTrivy_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: container
                          detection: auto
                        advanced:
                          log:
                            level: info
                        privileged: true
                        image:
                          type: docker_v2
                          name: alsharma9/juice-shop
                          tag: latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: Secure Image
        identifier: Secure_Image
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Security Test
                  identifier: Security_Test
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: true
                    approverInputs: []
        tags: {}
