pipeline:
  identifier: Build_kunalnano_juice_shop_1724968164902
  name: Build juice-shop
  orgIdentifier: TPMLabs
  projectIdentifier: testal
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1720712151481
        repoName: kunalnano/juice-shop
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: updateNode
                  name: Update Node.js Version
                  type: Run
                  spec:
                    shell: Sh
                    command: |-
                      # Download and install Node.js version 18.3
                      curl -fsSL https://deb.nodesource.com/setup_18.3 | bash -
                      apt-get install -y nodejs
                      # Verify Node.js version
                      node -v
              - step:
                  identifier: installdependencies
                  name: Install dependencies
                  spec:
                    shell: Sh
                    command: |-
                      npm install
                      npm install -g @angular/cli
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: Test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: lint
                  name: Lint
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: Docker Build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
