pipeline:
  identifier: Build_kunalnano_juice_shop_1724968164902
  name: Build juice-shop
  orgIdentifier: TPMLabs
  projectIdentifier: testal
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1720712151481
        repoName: kunalnano/juice-shop
  stages:
    - stage:
        identifier: build
        name: build
        type: CI
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installNode
                  name: Install Node.js Version
                  type: Run
                  spec:
                    shell: Sh
                    command: |-
                      # Install n package to manage Node.js versions
                      npm install -g n
                      # Install Node.js version 18.19 or higher
                      n 18.19.0
                      # Verify Node.js version
                      node -v
                      npm -v
              - step:
                  identifier: installdependencies
                  name: Install dependencies
                  type: Run
                  spec:
                    shell: Sh
                    command: |-
                      npm install
                      npm install -g @angular/cli
                    timeout: ""
              - step:
                  identifier: test
                  name: Test
                  type: Run
                  spec:
                    shell: Sh
                    command: npm run test
                    timeout: ""
              - step:
                  identifier: lint
                  name: Lint
                  type: Run
                  spec:
                    shell: Sh
                    command: npm run lint
                    timeout: ""
              - step:
                  identifier: dockerbuild
                  name: Docker Build
                  type: BuildAndPushDockerRegistry
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                    timeout: ""
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
