pipeline:
  identifier: Build_kunalnano_juice_shop_1725034562262
  name: Vulnerable juice-shop
  orgIdentifier: TPMLabs
  projectIdentifier: testal
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1720712151481
        repoName: kunalnano/juice-shop
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: Vulnerable_Juice_Shop
          versionLabel: a1
  tags: {}
