name: SCA with Snyk

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Python dependencies
      run: |
        if [ -f Pipfile ]; then
          pip install pipenv && pipenv install
        elif [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Install Node.js dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        fi

    - name: Install Java dependencies
      run: |
        if [ -f pom.xml ]; then
          mvn dependency:resolve
        fi

    - name: Snyk Scan
      uses: snyk/actions/setup@v1
      with:
        snyk-token: ${{ secrets.SNYK_TOKEN }}
    - run: snyk test --all-projects

